Subjective questionnaire
========================================================



```{r init, results='hide'}
#install.packages(c("ggplot2", "doBy"))
require(ggplot2)
require(doBy)
require(psych)
library(reshape2)
require(xtable)


data <- read.csv(file="data/Resultados.csv", head=TRUE, skip=1, sep=",")
names(data)
```

## Demographics

```{r demographics, results='asis', cache=TRUE}

s <- describe(data[,c(4:9)])
s <- cbind(Device=rownames(s), s)

rownames(s)<-NULL

print(xtable(s), type = "html")
      
write.table(s, file = "tables/questionnaire-demographics-summary.csv", sep=",", row.names=FALSE)
```

```{r mouse, results='asis'}
s <- describe(data[,c(10:21)])
s <- cbind(Device=rownames(s), s)

rownames(s)<-NULL
print(xtable(s), type = "html")


write.table(s, file = "tables/questionnaire-mouse-summary.csv", sep=",", row.names=FALSE)
```

```{r leapmotionscreentap, results='asis', cache=TRUE}

s <- describe(data[,c(23:34)])
s <- cbind(Device=rownames(s), s)

rownames(s)<-NULL
print(xtable(s), type = "html")
      
write.table(s, file = "tables/questionnaire-leapmotionscreentap-summary.csv", sep=",", row.names=FALSE)
```

```{r leapmotionhandgrab, results='asis', cache=TRUE}
s <- describe(data[,c(36:47)])
s <- cbind(Device=rownames(s), s)

rownames(s)<-NULL
print(xtable(s), type = "html")
write.table(s, file = "tables/questionnaire-leapmotionhandgrab-summary.csv", sep=",", row.names=FALSE)
```


All users indicated that their favorite device was the mouse. 
Regarding the two gestures users answered:
```{r devicepreference, results='asis', cache=TRUE}
s <- data[,c(1,50:53)]
smelted<-melt(s, id=c("ID"))
smelted$value <- factor(smelted$value)
levels(smelted$value) <- list( LeapMotionScreenTap=c("Touchless"), LeapMotionHandGrab=c("Grabbing") )
colnames(smelted)[2] = "Question"
colnames(smelted)[3] = "Gesture"
#s <- cbind(Device=rownames(s), s)

#put an "?" at the end, and replace "." with a space.
smelted$Question<-gsub("\\.$", "?", smelted$Question)
smelted$Question<-gsub("\\.", " ", smelted$Question)

ggplot(smelted, aes( x=Question) ) +
    geom_histogram(aes( colour=Question, fill=Question)) +
    facet_wrap( ~ Gesture, nrow=4) +
    scale_fill_brewer(palette="Set1") + 
    scale_colour_brewer(palette="Set1") + 
    theme(panel.margin = unit(2, "lines")) +
    theme(legend.position="top", 
          legend.direction="vertical", 
          legend.text=element_text(size=12),
          legend.title=element_text(size=14)) +
    theme(axis.text.x = element_blank() ) +
    #theme(strip.text.x = element_text(angle=65, hjust=0)) +
    ylab("Frequency") +
    #xlab("") +
    theme()
ggsave(file = "charts/questionnaire/gesture-preference.pdf", width=14/2.54, height=14/2.54, dpi=100)
```


```{r boxplots, cache=TRUE}
#####
m <- NULL
for (i in 10:21) {
  print(colnames(data)[i])
  c1 <- colnames(data)[i]
  c2 <- paste(c1,".1", sep="")
  c3 <- paste(c1,".2", sep="")
  
  m1 <- melt(data[,c("ID", c1, c2, c3)], id=c("ID"))
  colnames(m1) <- c("ID", "Device", c1) 
  levels(m1$Device) <- list( Mouse=c(c1),  LeapMotionScreenTap=c(c2), LeapMotionHandGrab=c(c3) )
  if ( is.null(m) ) {
    m <- m1
  } else{
    m<-cbind(m, c=m1[,c(c1)] )  
    colnames(m)[colnames(m) == "c"] <- c1
  }
  
}


m<-melt(m, id=c("ID", "Device"))


ggplot(m, aes(Device, value, colour=Device)) + 
  geom_boxplot() +
  #coord_flip() +
  facet_wrap(  ~ variable,ncol=3)
ggsave(file = "charts/questionnaire/iso-boxplot.pdf", width=21/2.54, height=29/2.54, dpi=100)
```

```{r barplot}
describe <- describeBy(m$value, list(m$Device,m$variable), mat=TRUE)
colnames(describe)[colnames(describe)=="group1"] <- "Device"
colnames(describe)[colnames(describe)=="group2"] <- "variable"
#Reorder levels for chart
levels(describe$Device) <- list( Mouse=c("Mouse"), LeapMotionScreenTap=c("LeapMotionScreenTap"), LeapMotionHandGrab=c("LeapMotionHandGrab"))
    


#dfc <- summarySE(m, measurevar="value", groupvars=c("Device","variable"))

ggplot(describe, aes(Device, mean, colour=Device, fill=Device)) + 
  #stat_summary(fun.y="mean", geom="bar") + 
 geom_bar(stat="identity") +
  #coord_flip() +
  geom_errorbar(aes(ymin=mean-1.96*se, ymax=mean+1.96*se), colour="Black",
               width=.2,                    # Width of the error bars
               position=position_dodge(.9)) +
  facet_wrap(  ~ variable,ncol=3) +
  theme(legend.position="top", 
        legend.direction="horizontal") 
ggsave(file = "charts/questionnaire/iso-barplot.pdf", width=16/2.54, height=20/2.54, dpi=100)
```


```{r barplotall, cache=TRUE, fig.width=20, fig.height=7}

describe$l <- ifelse(describe$Device=="Mouse", as.character(describe$variable), NA)

ggplot(describe, aes(x=variable, y=mean, group=Device, colour=Device, fill=Device, label=l) ) + 
    #stat_summary(fun.y="mean", geom="bar") + 
    geom_bar(stat="identity", width=.5, position = position_dodge(width=0.5)) +
    geom_text(angle=70, colour="Black", y=1.05,
              hjust=0, size=4) + 
    #geom_bar() +
    #coord_flip() +
    coord_cartesian(ylim=c(1.0, 5)) +
    ylab("Average score") +
    xlab("") +
    geom_errorbar(aes(ymin=mean-1.96*se, ymax=mean+1.96*se), colour="Black",
                  width=.2,                    # Width of the error bars
                  size = .1,
                  position=position_dodge(.5)) +
    #facet_wrap(  ~ variable,ncol=3) +
    theme(legend.position=c(.5,-0.1), legend.direction="horizontal", 
          axis.text.x = element_blank()) + 
    scale_fill_brewer(palette="Set1") + 
    scale_colour_brewer(palette="Set1")
    ggsave(file = "charts/questionnaire/iso-barplot-side.pdf", width=30/2.54, height=7/2.54, dpi=100)

```


